#!/bin/bash
reg=${1-localhost:5000}
cd test
echo ----- about to build and push to $reg
sleep 3
(cat Dockerfile; echo 'RUN echo' `date` '>> /usr/share/nginx/html/index.html') > Dockerfile.gen
docker build -t $reg/nginx:latest -f Dockerfile.gen .
docker push $reg/nginx:latest
echo ----- pushed
docker ps
sleep 15
docker ps
